name: LaTeX Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'cv.tex'
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy LaTeX Document
    runs-on: ubuntu-latest
    environment: unique

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up LaTeX environment
        uses: dante-ev/latex-action@latest

      - name: Compile LaTeX document
        run: |
          latexmk -pdf -interaction=nonstopmode -halt-on-error cv.tex

      - name: Commit and Push PDF
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add cv.pdf
          git commit -m "Automated update of cv.pdf"
          git push https://$TOKEN@github.com/${{ github.repository }} HEAD:main
