name: LaTeX Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'cv.tex'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build and Deploy LaTeX Document
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex

      - name: Commit and Push PDF
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add cv.pdf
          git commit -m "Automated update of cv.pdf"
          git push
